import { Company } from '../types';

export const anthropic: Company = {
  id: 'anthropic',
  name: 'Anthropic',
  logo: '🔬',
  color: '#D4A574',
  description: 'Build safe, beneficial AI systems. Join the team behind Claude to provide world-class support, architect solutions, and advocate for developers building with frontier AI models.',
  industry: 'AI Safety & Research',
  website: 'https://anthropic.com',
  roles: [
    {
      id: 'support-engineer',
      title: 'Support Engineer',
      icon: '🛠️',
      description: 'Provide expert technical support for Claude API users, debug complex integration issues, and help customers build reliable AI-powered applications.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'auth-security'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'networking', 'debugging'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'ai-llm', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'networking' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'solutions-architect',
      title: 'Solutions Architect',
      icon: '🏗️',
      description: 'Design and architect enterprise-scale AI solutions using Claude, guide technical decision-making, and bridge the gap between customer needs and Anthropic\'s capabilities.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'networking'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['auth-security', 'sql-data', 'ai-llm'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['enterprise-support', 'dev-tools', 'debugging'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'dev-tools' },
        { trackId: 'debugging' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'developer-advocate',
      title: 'Developer Advocate',
      icon: '📢',
      description: 'Champion the developer experience for Claude, create technical content, build sample applications, and represent Anthropic at conferences and in the developer community.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'ai-llm'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['dev-tools', 'debugging', 'soft-skills'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['auth-security', 'networking', 'sql-data'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['enterprise-support', 'compliance'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'dev-tools' },
        { trackId: 'debugging' },
        { trackId: 'soft-skills' },
        { trackId: 'auth-security' },
        { trackId: 'networking' },
        { trackId: 'sql-data' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
      ],
    },
  ],
};
