import { Company } from '../types';

export const aws: Company = {
  id: 'aws',
  name: 'AWS',
  logo: '☁️',
  color: '#FF9900',
  description: 'Support and architect on the world\'s most comprehensive cloud platform. Help businesses of all sizes leverage 200+ services spanning compute, storage, AI/ML, databases, and more.',
  industry: 'Cloud Infrastructure',
  website: 'https://aws.amazon.com',
  roles: [
    {
      id: 'cloud-support-engineer',
      title: 'Cloud Support Engineer',
      icon: '🛠️',
      description: 'Provide expert technical support for AWS services, troubleshoot complex cloud infrastructure issues, and help customers optimize their AWS deployments for cost and performance.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'networking', 'apis'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'auth-security', 'debugging', 'aws-services'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'ai-llm', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'networking' },
        { trackId: 'apis' },
        { trackId: 'sql-data' },
        { trackId: 'auth-security' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'aws-services' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'solutions-architect',
      title: 'Solutions Architect',
      icon: '🏗️',
      description: 'Design resilient, cost-optimized cloud architectures on AWS. Guide enterprises through migrations, multi-account strategies, and Well-Architected Framework reviews.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'networking', 'auth-security'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'apis', 'ai-llm', 'aws-services'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['enterprise-support', 'debugging', 'dev-tools'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'aws-services' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'technical-account-manager',
      title: 'Technical Account Manager',
      icon: '🤝',
      description: 'Be the trusted technical advisor for AWS Enterprise Support customers. Proactively guide architecture decisions, coordinate incident response, and drive cloud adoption best practices.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'soft-skills'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['networking', 'auth-security', 'enterprise-support', 'aws-services'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['sql-data', 'debugging', 'ai-llm'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['dev-tools', 'compliance'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'soft-skills' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'enterprise-support' },
        { trackId: 'sql-data' },
        { trackId: 'debugging' },
        { trackId: 'ai-llm' },
        { trackId: 'dev-tools' },
        { trackId: 'aws-services' },
        { trackId: 'compliance' },
      ],
    },
  ],
};
