import { Company } from '../types';

export const google: Company = {
  id: 'google',
  name: 'Google',
  logo: '🔍',
  color: '#4285F4',
  description: 'Join Google Cloud to support the world\'s most comprehensive cloud platform. Help enterprises leverage Vertex AI, BigQuery, and Google\'s full cloud ecosystem.',
  industry: 'Cloud & AI',
  website: 'https://cloud.google.com',
  roles: [
    {
      id: 'support-engineer',
      title: 'Support Engineer',
      icon: '🛠️',
      description: 'Provide expert technical support for Google Cloud products, debug infrastructure issues, and help customers optimize their cloud deployments.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'networking'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'auth-security', 'debugging'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'ai-llm', 'enterprise-support', 'google-cloud'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'networking' },
        { trackId: 'sql-data' },
        { trackId: 'auth-security' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'google-cloud' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'cloud-solutions-architect',
      title: 'Cloud Solutions Architect',
      icon: '☁️',
      description: 'Design and implement cloud architectures on GCP, guide enterprise migrations, and build reference architectures using Vertex AI, BigQuery, and Google Kubernetes Engine.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'networking', 'apis'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'auth-security', 'ai-llm', 'google-cloud'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['enterprise-support', 'debugging', 'dev-tools'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'networking' },
        { trackId: 'apis' },
        { trackId: 'sql-data' },
        { trackId: 'auth-security' },
        { trackId: 'ai-llm' },
        { trackId: 'google-cloud' },
        { trackId: 'enterprise-support' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'developer-relations-engineer',
      title: 'Developer Relations Engineer',
      icon: '🤝',
      description: 'Build and nurture Google\'s developer community, create technical content and sample apps for Google Cloud and AI products, and represent Google at developer events worldwide.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'ai-llm'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['dev-tools', 'soft-skills', 'debugging'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['networking', 'auth-security', 'sql-data', 'google-cloud'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['enterprise-support', 'compliance'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'dev-tools' },
        { trackId: 'soft-skills' },
        { trackId: 'debugging' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'google-cloud' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
      ],
    },
  ],
};
