import { Company } from '../types';

export const meta: Company = {
  id: 'meta',
  name: 'Meta',
  logo: '♾️',
  color: '#0668E1',
  description: 'Support the infrastructure behind Facebook, Instagram, and WhatsApp at planetary scale. Join a team that values production engineering culture, reliability, and open-source innovation.',
  industry: 'Social & Infrastructure',
  website: 'https://meta.com',
  roles: [
    {
      id: 'support-engineer',
      title: 'Support Engineer',
      icon: '🛠️',
      description: 'Provide technical support for Meta\'s developer platform, including Graph API, WhatsApp Business API, and Meta\'s advertising tools.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'networking'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'auth-security', 'debugging', 'meta-infra'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'ai-llm', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'networking' },
        { trackId: 'sql-data' },
        { trackId: 'auth-security' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'meta-infra' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'production-engineer',
      title: 'Production Engineer (SRE)',
      icon: '⚙️',
      description: 'Ensure the reliability and performance of Meta\'s infrastructure at billion-user scale. Combine software engineering with systems expertise to keep the world connected.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'networking', 'debugging'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'auth-security', 'dev-tools', 'meta-infra'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['apis', 'ai-llm', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'networking' },
        { trackId: 'debugging' },
        { trackId: 'sql-data' },
        { trackId: 'auth-security' },
        { trackId: 'dev-tools' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'enterprise-support' },
        { trackId: 'meta-infra' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'developer-advocate',
      title: 'Developer Advocate',
      icon: '📢',
      description: 'Grow Meta\'s developer ecosystem around open-source AI (LLaMA), React, PyTorch, and Meta\'s platform APIs through content, community building, and developer tooling.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'ai-llm'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['dev-tools', 'soft-skills', 'debugging'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['networking', 'auth-security', 'sql-data', 'meta-infra'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['enterprise-support', 'compliance'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'dev-tools' },
        { trackId: 'soft-skills' },
        { trackId: 'debugging' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'enterprise-support' },
        { trackId: 'meta-infra' },
        { trackId: 'compliance' },
      ],
    },
  ],
};
