import { Company } from '../types';

export const openai: Company = {
  id: 'openai',
  name: 'OpenAI',
  logo: '🤖',
  color: '#10A37F',
  description: 'Shape the future of AI at the company behind GPT and ChatGPT. Support developers building with the most widely adopted AI platform, architect scalable solutions, and drive developer adoption.',
  industry: 'AI Research & Products',
  website: 'https://openai.com',
  roles: [
    {
      id: 'support-engineer',
      title: 'Support Engineer',
      icon: '🛠️',
      description: 'Help developers integrate GPT models, troubleshoot API issues, and ensure smooth adoption of OpenAI\'s platform across diverse use cases.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'auth-security'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'networking', 'debugging'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'ai-llm', 'openai-api-deep', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'networking' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'openai-api-deep' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'solutions-architect',
      title: 'Solutions Architect',
      icon: '🏗️',
      description: 'Design enterprise AI architectures using GPT models, guide customers on fine-tuning strategies, and build reference implementations for complex use cases.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'networking'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['auth-security', 'sql-data', 'ai-llm', 'openai-api-deep'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['enterprise-support', 'dev-tools', 'debugging'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['compliance', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'networking' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'ai-llm' },
        { trackId: 'openai-api-deep' },
        { trackId: 'enterprise-support' },
        { trackId: 'dev-tools' },
        { trackId: 'debugging' },
        { trackId: 'compliance' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'developer-advocate',
      title: 'Developer Advocate',
      icon: '📢',
      description: 'Grow the OpenAI developer ecosystem through technical content, community engagement, and developer tooling that makes building with GPT models accessible to all.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'ai-llm', 'openai-api-deep'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['dev-tools', 'debugging', 'soft-skills'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['auth-security', 'networking', 'sql-data'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['enterprise-support', 'compliance'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'ai-llm' },
        { trackId: 'openai-api-deep' },
        { trackId: 'dev-tools' },
        { trackId: 'debugging' },
        { trackId: 'soft-skills' },
        { trackId: 'auth-security' },
        { trackId: 'networking' },
        { trackId: 'sql-data' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
      ],
    },
  ],
};
