import { Company } from '../types';

export const stripe: Company = {
  id: 'stripe',
  name: 'Stripe',
  logo: '💳',
  color: '#635BFF',
  description: 'Power the internet\'s economic infrastructure. Help millions of businesses accept payments, manage subscriptions, and build financial platforms with Stripe\'s APIs.',
  industry: 'Fintech & Payments',
  website: 'https://stripe.com',
  roles: [
    {
      id: 'support-engineer',
      title: 'Support Engineer',
      icon: '🛠️',
      description: 'Help developers integrate Stripe\'s payment APIs, debug webhook issues, and ensure seamless checkout experiences for businesses worldwide.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'auth-security'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'networking', 'debugging', 'stripe-payments'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['dev-tools', 'enterprise-support', 'compliance'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['ai-llm', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'networking' },
        { trackId: 'debugging' },
        { trackId: 'stripe-payments' },
        { trackId: 'dev-tools' },
        { trackId: 'enterprise-support' },
        { trackId: 'compliance' },
        { trackId: 'ai-llm' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'solutions-architect',
      title: 'Solutions Architect',
      icon: '🏗️',
      description: 'Design complex payment architectures using Stripe Connect, Billing, and Treasury. Guide enterprises through PCI compliance, multi-currency setups, and marketplace payment flows.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'auth-security'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['sql-data', 'networking', 'compliance', 'stripe-payments'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['enterprise-support', 'debugging', 'dev-tools'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['ai-llm', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'auth-security' },
        { trackId: 'sql-data' },
        { trackId: 'networking' },
        { trackId: 'compliance' },
        { trackId: 'stripe-payments' },
        { trackId: 'enterprise-support' },
        { trackId: 'debugging' },
        { trackId: 'dev-tools' },
        { trackId: 'ai-llm' },
        { trackId: 'soft-skills' },
      ],
    },
    {
      id: 'integration-engineer',
      title: 'Integration Engineer',
      icon: '🔌',
      description: 'Build and maintain Stripe\'s client libraries, SDKs, and integration tools. Ensure developers across every language and framework can integrate payments seamlessly.',
      duration: '24 months',
      phases: [
        {
          phase: 1,
          title: 'Foundation',
          months: '1–6',
          color: '#3B82F6',
          trackIds: ['core-lang', 'apis', 'dev-tools'],
        },
        {
          phase: 2,
          title: 'Core Skills',
          months: '7–12',
          color: '#8B5CF6',
          trackIds: ['auth-security', 'networking', 'debugging', 'stripe-payments'],
        },
        {
          phase: 3,
          title: 'Advanced',
          months: '13–18',
          color: '#F59E0B',
          trackIds: ['sql-data', 'compliance', 'enterprise-support'],
        },
        {
          phase: 4,
          title: 'Expert',
          months: '19–24',
          color: '#EF4444',
          trackIds: ['ai-llm', 'soft-skills'],
        },
      ],
      trackRefs: [
        { trackId: 'core-lang' },
        { trackId: 'apis' },
        { trackId: 'dev-tools' },
        { trackId: 'auth-security' },
        { trackId: 'networking' },
        { trackId: 'debugging' },
        { trackId: 'stripe-payments' },
        { trackId: 'sql-data' },
        { trackId: 'compliance' },
        { trackId: 'enterprise-support' },
        { trackId: 'ai-llm' },
        { trackId: 'soft-skills' },
      ],
    },
  ],
};
